export default {
  LOAD_CHARACTERS: 'LOAD_CHARACTERS',
  LOAD_SEARCHED_CHARACTERS: 'LOAD_SEARCHED_CHARACTERS',

  LOAD_PLANET: 'LOAD_PLANET',

  LOAD_PEOPLE_FROM_PLANET: 'LOAD_PEOPLE_FROM_PLANET',

  API_ERROR: 'API_ERROR',
};
